### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by syptic** [dennisliang01/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
The first bug commit doesn't reflect significant code change, you merely added a print statement which might be useful for debugging but doesn't solve the issue at hand. Try to stop the infinite loop by detecting the issue and exiting out of the loop.

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by dennisliang01** [comment]
Fixed the listed issue by implementing more significant changes that detect if there is an extra ) character and break out of the infinite loop. Left check box unchecked for grader purpose.
